-- =====================================================================
-- Esquema inicial de la herramienta de gestion de estrategias de respaldo.
-- Flujo que soporta el modelo:
--   estrategia -> validacion -> script -> aprobacion -> programacion
--   -> ejecucion -> evidencia -> alertas
-- Booleanos como NUMBER(1) (Oracle 21 no tiene BOOLEAN en SQL).
-- =====================================================================

-- Base de datos Oracle registrada (la que se respalda, no la de la app).
CREATE TABLE base_datos (
    id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(100)  NOT NULL,
    descripcion       VARCHAR2(500),
    contenedor        VARCHAR2(100)  NOT NULL,   -- contenedor Docker donde corre RMAN
    servicio          VARCHAR2(100)  NOT NULL,   -- servicio Oracle (p. ej. XEPDB1)
    ambiente          VARCHAR2(20)   NOT NULL,
    modo_archivado    VARCHAR2(20),              -- se llena al inspeccionar; NULL = desconocido
    fecha_inspeccion  TIMESTAMP,
    fecha_registro    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_base_datos_nombre UNIQUE (nombre),
    CONSTRAINT ck_base_datos_ambiente CHECK (ambiente IN ('DESARROLLO', 'PRUEBAS', 'PRODUCCION')),
    CONSTRAINT ck_base_datos_modo CHECK (modo_archivado IN ('ARCHIVELOG', 'NOARCHIVELOG'))
);

-- Estrategia: informacion general + COMO + destino.
-- El QUE va en estrategia_elemento y el CUANDO en programacion.
CREATE TABLE estrategia (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(100)  NOT NULL,
    descripcion         VARCHAR2(1000),
    base_datos_id       NUMBER(19)     NOT NULL,
    responsable         VARCHAR2(100)  NOT NULL,
    prioridad           VARCHAR2(10)   NOT NULL,
    activa              NUMBER(1)      DEFAULT 0 NOT NULL,
    -- COMO
    tipo_respaldo       VARCHAR2(40)   NOT NULL,
    comprimido          NUMBER(1)      DEFAULT 0 NOT NULL,
    dias_retencion      NUMBER(5),
    -- Destino
    ruta_destino        VARCHAR2(500)  NOT NULL,
    dispositivo         VARCHAR2(20)   DEFAULT 'DISK' NOT NULL,
    fecha_creacion      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_modificacion  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_estrategia_nombre UNIQUE (nombre),
    CONSTRAINT fk_estrategia_base FOREIGN KEY (base_datos_id) REFERENCES base_datos (id),
    CONSTRAINT ck_estrategia_prioridad CHECK (prioridad IN ('ALTA', 'MEDIA', 'BAJA')),
    CONSTRAINT ck_estrategia_activa CHECK (activa IN (0, 1)),
    CONSTRAINT ck_estrategia_tipo CHECK (tipo_respaldo IN (
        'COMPLETO',
        'INCREMENTAL_NIVEL_0',
        'INCREMENTAL_NIVEL_1_DIFERENCIAL',
        'INCREMENTAL_NIVEL_1_ACUMULATIVO')),
    CONSTRAINT ck_estrategia_comprimido CHECK (comprimido IN (0, 1)),
    CONSTRAINT ck_estrategia_retencion CHECK (dias_retencion IS NULL OR dias_retencion > 0),
    CONSTRAINT ck_estrategia_dispositivo CHECK (dispositivo IN ('DISK'))
);
CREATE INDEX ix_estrategia_base ON estrategia (base_datos_id);

-- QUE respaldar: un registro por elemento incluido en la estrategia.
-- nombre_objeto es obligatorio solo para TABLESPACE (nombre) y DATAFILE (numero o ruta).
CREATE TABLE estrategia_elemento (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estrategia_id  NUMBER(19)    NOT NULL,
    tipo_elemento  VARCHAR2(20)  NOT NULL,
    nombre_objeto  VARCHAR2(500),
    CONSTRAINT fk_elemento_estrategia FOREIGN KEY (estrategia_id)
        REFERENCES estrategia (id) ON DELETE CASCADE,
    CONSTRAINT ck_elemento_tipo CHECK (tipo_elemento IN (
        'BASE_DATOS', 'TABLESPACE', 'DATAFILE', 'CONTROLFILE', 'SPFILE', 'ARCHIVELOG')),
    CONSTRAINT ck_elemento_nombre CHECK (
        (tipo_elemento IN ('TABLESPACE', 'DATAFILE') AND nombre_objeto IS NOT NULL)
        OR (tipo_elemento NOT IN ('TABLESPACE', 'DATAFILE') AND nombre_objeto IS NULL)),
    CONSTRAINT uq_elemento UNIQUE (estrategia_id, tipo_elemento, nombre_objeto)
);

-- CUANDO respaldar: una programacion por estrategia.
-- hora y ventana en formato HH:MM (24 h). dias_semana: 'LUN,MIE,VIE' para SEMANAL.
-- intervalo: cada cuantas horas (CADA_N_HORAS) o cada cuantos dias/semanas/meses.
CREATE TABLE programacion (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estrategia_id       NUMBER(19)    NOT NULL,
    fecha_inicio        DATE          NOT NULL,
    hora                VARCHAR2(5)   NOT NULL,
    frecuencia          VARCHAR2(20)  NOT NULL,
    dias_semana         VARCHAR2(30),
    intervalo           NUMBER(4)     DEFAULT 1 NOT NULL,
    ventana_inicio      VARCHAR2(5),
    ventana_fin         VARCHAR2(5),
    activa              NUMBER(1)     DEFAULT 1 NOT NULL,
    proxima_ejecucion   TIMESTAMP,
    fecha_modificacion  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_programacion_estrategia UNIQUE (estrategia_id),
    CONSTRAINT fk_programacion_estrategia FOREIGN KEY (estrategia_id)
        REFERENCES estrategia (id) ON DELETE CASCADE,
    CONSTRAINT ck_programacion_frecuencia CHECK (frecuencia IN (
        'UNA_VEZ', 'CADA_N_HORAS', 'DIARIA', 'SEMANAL', 'MENSUAL')),
    CONSTRAINT ck_programacion_hora CHECK (REGEXP_LIKE(hora, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT ck_programacion_vini CHECK (ventana_inicio IS NULL
        OR REGEXP_LIKE(ventana_inicio, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT ck_programacion_vfin CHECK (ventana_fin IS NULL
        OR REGEXP_LIKE(ventana_fin, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT ck_programacion_intervalo CHECK (intervalo > 0),
    CONSTRAINT ck_programacion_semanal CHECK (frecuencia <> 'SEMANAL' OR dias_semana IS NOT NULL),
    CONSTRAINT ck_programacion_activa CHECK (activa IN (0, 1))
);

-- Script RMAN generado a partir de la estrategia.
-- hash_configuracion: huella de la estrategia al generarlo. Si la estrategia cambia,
-- la huella deja de coincidir y la aprobacion queda invalidada.
-- hash_contenido: huella del texto exacto que el administrador aprobo.
CREATE TABLE script_rman (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estrategia_id       NUMBER(19)    NOT NULL,
    version             NUMBER(10)    NOT NULL,
    contenido           CLOB          NOT NULL,
    hash_contenido      VARCHAR2(64)  NOT NULL,
    hash_configuracion  VARCHAR2(64)  NOT NULL,
    estado              VARCHAR2(20)  DEFAULT 'GENERADO' NOT NULL,
    fecha_generacion    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    aprobado_por        VARCHAR2(100),
    fecha_aprobacion    TIMESTAMP,
    CONSTRAINT fk_script_estrategia FOREIGN KEY (estrategia_id) REFERENCES estrategia (id),
    CONSTRAINT uq_script_version UNIQUE (estrategia_id, version),
    CONSTRAINT ck_script_estado CHECK (estado IN ('GENERADO', 'APROBADO', 'RECHAZADO', 'INVALIDADO')),
    CONSTRAINT ck_script_aprobacion CHECK (
        estado <> 'APROBADO' OR (aprobado_por IS NOT NULL AND fecha_aprobacion IS NOT NULL))
);

-- Ejecucion de un script (evidencia). Guarda copias de lo que se ejecuto
-- (tipo de respaldo, script, destino) para que el historial no dependa de
-- cambios posteriores en la estrategia.
CREATE TABLE ejecucion (
    id                   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estrategia_id        NUMBER(19)     NOT NULL,
    script_id            NUMBER(19)     NOT NULL,
    base_datos_id        NUMBER(19)     NOT NULL,
    origen               VARCHAR2(20)   NOT NULL,
    estado               VARCHAR2(20)   NOT NULL,
    tipo_respaldo        VARCHAR2(40)   NOT NULL,
    script_ejecutado     CLOB           NOT NULL,
    ruta_destino         VARCHAR2(500)  NOT NULL,
    fecha_programada     TIMESTAMP,
    fecha_inicio         TIMESTAMP      NOT NULL,
    fecha_fin            TIMESTAMP,
    duracion_segundos    NUMBER(10),
    codigo_salida        NUMBER(10),
    salida_rman          CLOB,
    mensaje_error        VARCHAR2(4000),
    tamano_total_bytes   NUMBER(19),
    verificacion         VARCHAR2(20)   DEFAULT 'PENDIENTE' NOT NULL,
    salida_verificacion  CLOB,
    CONSTRAINT fk_ejecucion_estrategia FOREIGN KEY (estrategia_id) REFERENCES estrategia (id),
    CONSTRAINT fk_ejecucion_script FOREIGN KEY (script_id) REFERENCES script_rman (id),
    CONSTRAINT fk_ejecucion_base FOREIGN KEY (base_datos_id) REFERENCES base_datos (id),
    CONSTRAINT ck_ejecucion_origen CHECK (origen IN ('MANUAL', 'PROGRAMADA')),
    CONSTRAINT ck_ejecucion_estado CHECK (estado IN (
        'EN_CURSO', 'EXITOSO', 'CON_ADVERTENCIAS', 'FALLIDO')),
    CONSTRAINT ck_ejecucion_verificacion CHECK (verificacion IN (
        'PENDIENTE', 'VERIFICADO', 'FALLIDA', 'NO_APLICA'))
);
CREATE INDEX ix_ejecucion_estrategia ON ejecucion (estrategia_id, fecha_inicio);
CREATE INDEX ix_ejecucion_script ON ejecucion (script_id);
CREATE INDEX ix_ejecucion_base ON ejecucion (base_datos_id);

-- Archivos producidos por una ejecucion (piece handles de RMAN) y si existen en disco.
CREATE TABLE evidencia_archivo (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ejecucion_id        NUMBER(19)     NOT NULL,
    ruta                VARCHAR2(1000) NOT NULL,
    tipo                VARCHAR2(30)   NOT NULL,
    tamano_bytes        NUMBER(19),
    existe              NUMBER(1)      DEFAULT 0 NOT NULL,
    fecha_verificacion  TIMESTAMP,
    CONSTRAINT fk_evidencia_ejecucion FOREIGN KEY (ejecucion_id)
        REFERENCES ejecucion (id) ON DELETE CASCADE,
    CONSTRAINT ck_evidencia_tipo CHECK (tipo IN ('PIEZA_RESPALDO', 'AUTORESPALDO_CONTROLFILE')),
    CONSTRAINT ck_evidencia_existe CHECK (existe IN (0, 1))
);
CREATE INDEX ix_evidencia_ejecucion ON evidencia_archivo (ejecucion_id);

-- Mensajes persistentes del control preventivo.
-- tipo: los tres tipos de mensaje que exige el proyecto.
-- estado APLICADA: solo para recomendaciones, y solo cuando el administrador
-- decide aplicarla (la app nunca la aplica sola).
CREATE TABLE alerta (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR2(20)   NOT NULL,
    codigo          VARCHAR2(50)   NOT NULL,
    mensaje         VARCHAR2(1000) NOT NULL,
    base_datos_id   NUMBER(19),
    estrategia_id   NUMBER(19),
    ejecucion_id    NUMBER(19),
    estado          VARCHAR2(20)   DEFAULT 'ABIERTA' NOT NULL,
    fecha_creacion  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_atencion  TIMESTAMP,
    atendida_por    VARCHAR2(100),
    comentario      VARCHAR2(1000),
    CONSTRAINT fk_alerta_base FOREIGN KEY (base_datos_id) REFERENCES base_datos (id),
    CONSTRAINT fk_alerta_estrategia FOREIGN KEY (estrategia_id) REFERENCES estrategia (id),
    CONSTRAINT fk_alerta_ejecucion FOREIGN KEY (ejecucion_id) REFERENCES ejecucion (id),
    CONSTRAINT ck_alerta_tipo CHECK (tipo IN ('INFORMATIVO', 'ADVERTENCIA', 'RECOMENDACION')),
    CONSTRAINT ck_alerta_estado CHECK (estado IN ('ABIERTA', 'ATENDIDA', 'DESCARTADA', 'APLICADA')),
    CONSTRAINT ck_alerta_aplicada CHECK (estado <> 'APLICADA' OR tipo = 'RECOMENDACION')
);
CREATE INDEX ix_alerta_estado ON alerta (estado, tipo);
CREATE INDEX ix_alerta_base ON alerta (base_datos_id);
CREATE INDEX ix_alerta_estrategia ON alerta (estrategia_id);
CREATE INDEX ix_alerta_ejecucion ON alerta (ejecucion_id);
